function X = aminoacid_to_codon(Y)
% Y is a character please insert it inside apostrophe
Aminoacid = {'Ala1';'Ala2';'Ala3';'Ala4';'Cys1';'Cys2';'Asp1';'Asp2';...
    'Glu1';'Glu2';'Phe1';'Phe2';'Gly1';'Gly2';'Gly3';'Gly4';'His1';...
    'His2';'Ile1';'Ile2';'Ile3';'Lys1';'Lys2';'Leu1';'Leu2';'Leu3';...
    'Leu4';'Leu5';'Leu6';'Met1';'Asn1';'Asn2';'Pro1';'Pro2';'Pro3';...
    'Pro4';'Gln1';'Gln2';'Arg1';'Arg2';'Arg3';'Arg4';'Arg5';'Arg6';...
    'Ser1';'Ser2';'Ser3';'Ser4';'Ser5';'Ser6';'Thr1';'Thr2';'Thr3';...
    'Thr4';'Val1';'Val2';'Val3';'Val4';'Trp1';'Tyr1';'Tyr2';'Stp1';...
    'Stp2';'Stp3'};
Codon = {'GCG';'GCA';'GCT';'GCC';'TGT';'TGC';'GAT';'GAC';'GAG';'GAA';...
    'TTT';'TTC';'GGG';'GGA';'GGT';'GGC';'CAT';'CAC';'ATA';'ATT';...
    'ATC';'AAG';'AAA';'TTG';'TTA';'CTG';'CTA';'CTT';'CTC';'ATG';...
    'AAT';'AAC';'CCG';'CCA';'CCT';'CCC';'CAG';'CAA';'AGG';'AGA';...
    'CGG';'CGA';'CGT';'CGC';'AGT';'AGC';'TCG';'TCA';'TCT';'TCC';...
    'ACG';'ACA';'ACT';'ACC';'GTG';'GTA';'GTT';'GTC';'TGG';'TAT';...
    'TAC';'TGA';'TAG';'TAA'};
for i=1:length(Y)
    if ismember(Y(i),Aminoacid) == 0
        fprintf('your desired Aminoacid name is not on the list \n or you may have the wrong name %d \n',i)
    else
        x = strfind(Aminoacid,Y(i));
        ind = find(~cellfun(@isempty,x)) ;
        X(i) = Codon(ind);
    end
end
X = X';
end

