function X = codon_to_aminoacid(Y)
% Y is a character please insert it inside apostrophe
Aminoacid = {'Ala';'Ala';'Ala';'Ala';'Cys';'Cys';'Asp';'Asp';...
    'Glu';'Glu';'Phe';'Phe';'Gly';'Gly';'Gly';'Gly';'His';...
    'His';'Ile';'Ile';'Ile';'Lys';'Lys';'Leu';'Leu';'Leu';...
    'Leu';'Leu5';'Leu6';'Met';'Asn';'Asn';'Pro';'Pro';'Pro';...
    'Pro';'Gln';'Gln';'Arg';'Arg';'Arg';'Arg';'Arg5';'Arg6';...
    'Ser';'Ser';'Ser';'Ser';'Ser5';'Ser6';'Thr';'Thr';'Thr';...
    'Thr';'Val';'Val';'Val';'Val';'Trp';'Tyr';'Tyr';'Stp';...
    'Stp';'Stp'};
Codon = {'GCG';'GCA';'GCT';'GCC';'TGT';'TGC';'GAT';'GAC';'GAG';'GAA';...
    'TTT';'TTC';'GGG';'GGA';'GGT';'GGC';'CAT';'CAC';'ATA';'ATT';...
    'ATC';'AAG';'AAA';'TTG';'TTA';'CTG';'CTA';'CTT';'CTC';'ATG';...
    'AAT';'AAC';'CCG';'CCA';'CCT';'CCC';'CAG';'CAA';'AGG';'AGA';...
    'CGG';'CGA';'CGT';'CGC';'AGT';'AGC';'TCG';'TCA';'TCT';'TCC';...
    'ACG';'ACA';'ACT';'ACC';'GTG';'GTA';'GTT';'GTC';'TGG';'TAT';...
    'TAC';'TGA';'TAG';'TAA'};
for i=1:length(Y)
    if ismember(Y(i),Codon) == 0
        fprintf('your desired amino acid sequence is not on the list \n or you may have the wrong name %d \n',i)
    else
        x = strfind(Codon,Y(i));
        ind = find(~cellfun(@isempty,x)) ;
        X{i} = Aminoacid{ind};
    end
end
% X = X';
end